# Generated by cucumber-sinatra. (2014-09-21 17:52:57 +0100)

ENV['RACK_ENV'] = 'test'

require File.join(File.dirname(__FILE__), '..', '..', 'server.rb')

require 'capybara'
require 'capybara/cucumber'
require 'rspec'

Capybara.app = GiftAidCalculatorApplication

class GiftAidCalculatorApplicationWorld
  include Capybara::DSL
  include RSpec::Expectations
  include RSpec::Matchers
end

World do
  GiftAidCalculatorApplicationWorld.new
end
